CREATE DATABASE PRUEBA;
USE PRUEBA;

CREATE TABLE COUNTRIES (
ID_COUNTRY INT(11) PRIMARY KEY,
NAME VARCHAR(80) NOT NULL
);
CREATE TABLE STATES (
ID_STATE INT(11) PRIMARY KEY,
NAME VARCHAR(80) NOT NULL,
ID_COUNTRY INT(11) REFERENCES COUNTRIES(ID_COUNTRY)
);
CREATE TABLE CITIES (
ID_CITY INT(11) PRIMARY KEY,
NAME VARCHAR(80) NOT NULL,
ID_STATE INT(11) REFERENCES STATES(ID_STATE),
POPULATION INTEGER NOT NULL
);
ALTER TABLE STATES
ADD FOREIGN KEY (ID_COUNTRY) REFERENCES COUNTRIES(ID_COUNTRY);
ALTER TABLE CITIES
ADD FOREIGN KEY (ID_STATE) REFERENCES STATES(ID_STATE)